"use client";
import { useEffect, useState, FC } from "react";

/*
  Welcome to the simplegamehosting coding assignment!

  if you got this far great job! 🎉
  Now it's your turn to shine! 🌟
  
  The mock data is fetched from the server and displayed on the page.

  Your task is to create a dynamic card component for each server in the list.
  - The card should display the server's name, game, players, status, version etc, bonus points for displaying any extra data from the json response.
  - please use tailwind to style your components, you can use the existing styles in this file as a reference.
  - You can also use any other libraries you like to help you build the UI.
  
  for extra info please read the README.md file in the root of the project.
*/

/* Individual type for the data representing a game server */
interface GameServer {
  id: number;
  name: string;
  game: string;
  players: string;
  status: string;
  version: string;
  type: string;
  region: string;
  mods: string[]
}

/* Type for the data passed into the server list component */
interface GameServerListProps {
  title: string;
  data: GameServer[];
}

/* Type for the data passed into the card component for displaying the actual server content */
interface GameServerProps {
  server: GameServer;
}

/* Component card for displaying all relevant data about a server */
const GameServer: FC<GameServerProps> = ({server}) => {

  return (
    <section>
      <div>{server.name}</div>
      <div>{server.players}</div>
      <div>
        <span></span>
        {server.status}
        <button>Stop/Start</button>
      </div>
      <div>
        Mods:
        <div></div>
      </div>
      <div>
        <div>{server.game}</div>
        <div>{server.version}</div>
        <div>{server.type}</div>
        <div>{server.region}</div>
      </div>
    </section>
  );
}


/* Container component for a list of Game server cards generated by the JSON array passed to it */
const GameServerList: FC<GameServerListProps> = ({data, title}) => {

  return (
    <main className="flex flex-col row-start-2 gap-10 bg-sky-950 p-10 rounded-lg text-sky-200">
      <h1 className="text-2xl font-bold text-sky-200">{title}</h1>
      {data.map(item => {
        return (
          <GameServer server={item} />
        )
      })}
    </main>
  );

}

export default function Home() {
  const [serverData, setServerData] = useState(null);
  // you can update this fetching code if required but it's not necessary for the assignment.
  useEffect(() => {
    const fetchServerData = async () => {
      try {
        const response = await fetch("/api/mock");
        const data = await response.json();
        setServerData(data);
      } catch (error) {
        console.error("Failed to fetch server data:", error);
      }
    };

    fetchServerData();
  }, []);

  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
      {serverData ? (<GameServerList title="Minecraft Server List" data={serverData} />) : "Loading..."}
    </div>
  );
}
